---
- name: Install dnf dependencies
  become: true
  ansible.builtin.dnf:
    name: dnf-plugins-core
    update_cache: true
    state: present
  register: dnf_dependencies_install
  ignore_errors: true

- name: Check for python3-libdnf5 error
  ansible.builtin.debug:
    msg: "Missing python3-libdnf5. Installing it now."
  when: "'python3-libdnf5' in dnf_dependencies_install.msg"

- name: Install python3-libdnf5 # noqa: no-changed-when
  become: true
  ansible.builtin.command:
    cmd: "dnf install -y python3-libdnf5 dnf-plugins-core"
  when: "'python3-libdnf5' in dnf_dependencies_install.msg"

- name: Add cloudflared repository
  become: true
  ansible.builtin.yum_repository:
    name: cloudflared-stable
    description: cloudflared-stable repository
    baseurl: https://pkg.cloudflare.com/cloudflared/rpm
    gpgcheck: true
    gpgkey: https://pkg.cloudflare.com/cloudflare-ascii-pubkey.gpg
    state: present

- name: Install cloudflared
  become: true
  ansible.builtin.dnf:
    name: cloudflared
    update_cache: true
    state: present
