---
- name: Converge
  hosts: all
  become: true

  roles:
    - role: sebdanielsson.cloudflared

  tasks:
    # 1. Test Installation
    - name: Include role to install cloudflared
      ansible.builtin.include_role:
        name: sebdanielsson.cloudflared
        state: present

    # Include some tasks here to verify the installation,
    # like checking if the service is running.

    # 2. Test Uninstallation
    - name: Include role to uninstall cloudflared
      ansible.builtin.include_role:
        name: sebdanielsson.cloudflared
        state: absent
