- name: Add cloudflared repository keyring
  become: true
  ansible.builtin.get_url:
    url: https://pkg.cloudflare.com/cloudflare-main.gpg
    dest: /usr/share/keyrings/cloudflare-main.gpg
    mode: 0644

- name: Add cloudflared repository
  become: true
  ansible.builtin.apt_repository:
    filename: cloudflared.list
    repo: "deb [signed-by=/usr/share/keyrings/cloudflare-main.gpg] https://pkg.cloudflare.com/cloudflared {{ ansible_distribution_release }} main"
    state: present

- name: Install cloudflared
  become: true
  ansible.builtin.apt:
    name:
      - cloudflared
    state: present
