---
- name: Ensure python3-debian is installed
  become: true
  ansible.builtin.apt:
    name: python3-debian
    update_cache: true
    state: present

- name: Check if cloudflare repository exists but is not using 'any' suite
  become: true
  ansible.builtin.slurp:
    path: "/etc/apt/sources.list.d/cloudflare.sources"
  register: cloudflare_repo_content
  failed_when: false

- name: Remove deprecated cloudflare repository (not using 'any' suite)
  become: true
  ansible.builtin.file:
    path: "/etc/apt/sources.list.d/cloudflare.sources"
    state: absent
  when:
    - cloudflare_repo_content.content is defined
    - '"Suites: any" not in (cloudflare_repo_content.content | b64decode)'

- name: Add cloudflared repository
  become: true
  ansible.builtin.deb822_repository:
    name: cloudflare
    types: deb
    uris: https://pkg.cloudflare.com/cloudflared
    suites: any
    components: main
    signed_by: https://pkg.cloudflare.com/cloudflare-main.gpg
    state: present

- name: Install cloudflared
  become: true
  ansible.builtin.apt:
    name: cloudflared
    update_cache: true
    state: present
