---
- name: Uninstall cloudflared
  become: true
  ansible.builtin.apt:
    name:
      - cloudflared
    state: absent

- name: Remove cloudflared repository
  become: true
  ansible.builtin.deb822_repository:
    name: cloudflare
    types: deb
    uris: https://pkg.cloudflare.com/cloudflared
    suites: any
    components: main
    signed_by: https://pkg.cloudflare.com/cloudflare-main.gpg
    state: absent

- name: Remove deprecated flavor-specific cloudflared repository
  become: true
  ansible.builtin.deb822_repository:
    name: cloudflare
    types: deb
    uris: https://pkg.cloudflare.com/cloudflared
    suites: "{{ ansible_distribution_release }}"
    components: main
    signed_by: https://pkg.cloudflare.com/cloudflare-main.gpg
    state: absent
