name: ansible-lint
on: [push, pull_request]

jobs:
  build:
    name: Ansible Lint
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 0

      - name: Run ansible-lint
        uses: ansible/ansible-lint-action@v6.11.0
